### ISSUE TITLE
MQTT user/password authentication

### ISSUE THREAD

**Issue by Paul-Simpson** [PerMalmberg/Smooth#168]
Hello,

Again, thank you for sharing this framework with the world. 

I'm returning to my project and since updating to IDF4.2 and Moquitto 6.0.1, I'm having connection issues with MQTT.

I think it might be something to do with authentication, so I've tried adding a user/passwd but don't see anywhere to do that. Unless I'm missing something, Smooth does support that? I also looked to see if Smooth supports SSL/TLS encryption. Is ConnectToBrokerState.cpp the right place to look at? Btw, have you implemented your own MQTT protocol from the group up?

Many thanks again for any advice or help,

Paul

**Comment by Paul-Simpson** [comment]
Update: The fork looks promising, however, I'm having trouble compiling it with:

**Comment by PerMalmberg** [comment]
I'm guessing it is part of ESP-IDF?

**Comment by Paul-Simpson** [comment]
Yes. I can see the file. Vscode can even follow the include link. I'll look further into it.

**Comment by Paul-Simpson** [comment]
Hi, quick update. I've been looking at the luuvt mqtts fork. It works well with ESP-IDF 4.2.x, but I'm seeing compile errors when using with 4.3 or 4.4. The errors are:

```
In file included from /Users/paulsimpson/esp/esp-idf/components/driver/include/driver/gpio.h:16,
                 from ../externals/smooth/lib/smooth/include/smooth/core/io/spi/Master.h:24,
                 from ../externals/smooth/lib/smooth/include/smooth/application/io/spi/BME280SPI.h:30,
                 from ../externals/smooth/lib/smooth/application/io/spi/BME280SPI.cpp:19:
/Users/paulsimpson/esp/esp-idf/components/hal/include/hal/spi_types.h: In function 'constexpr spi_event_t operator~(spi_event_t)':
/Users/paulsimpson/esp/esp-idf/components/esp_common/include/esp_attr.h:123:79: error: use of old-style cast to 'uint32_t' {aka 'unsigned int'} [-Werror=old-style-cast]
 FORCE_INLINE_ATTR constexpr TYPE operator~ (TYPE a) { return (TYPE)~(INT_TYPE)a; } \
                                                                               ^
/Users/paulsimpson/esp/esp-idf/components/esp_common/include/esp_attr.h:135:29: note: in expansion of macro 'FLAG_ATTR_IMPL'
 #define FLAG_ATTR_U32(TYPE) FLAG_ATTR_IMPL(TYPE, uint32_t)
                             ^~~~~~~~~~~~~~
/Users/paulsimpson/esp/esp-idf/components/esp_common/include/esp_attr.h:136:19: note: in expansion of macro 'FLAG_ATTR_U32'
 #define FLAG_ATTR FLAG_ATTR_U32
                   ^~~~~~~~~~~~~
```

...is this something that you have seen before? I'm pretty green to PR's etc on GitHub, so please don't be afraid to spell out how I can be of help getting this fixed and in a state where I can PR it. Best Wishes, Paul

**Comment by PerMalmberg** [comment]
I think this original repo is compatible with 4.3 and 4.4, if I remember correctly another contributor made PR to fix it.

If you can compile this original Smooth repo with them, it's probably easiest to simply look at what luuvt has done and make new PR with those changes and any improvements on top.

I've been busy with other things for the last two years so I don't have the environment, nor the time, to investigate it myself.

**Comment by Paul-Simpson** [comment]
Hey - thanks for the pointers. I looked into this issue some more. The latest Smooth compiles just fine with 4.4, so I will look at how I can bring the luuvt mqtts changes into the latest Smooth and then PR that as you suggest. 

Aside from the issue, I must say that I'm learning positively a lot from your code and architecture. :) Out of interest (and please feel free not to answer if you're busy) would you have structured it in the same way if you were to start again? I'm asking not because I see any issues, but because by the time I finished building a project,  many lessons have been learnt along the way.

**Comment by PerMalmberg** [comment]
> Out of interest (and please feel free not to answer if you're busy) would you have structured it in the same way if you were to start again?

Yes, and no. As with every software project, you learn things as it progresses and there are always things that can be done better. Smooth is actually based on similar software system that I developed and is running on thousands of systems at airports all over the world. I've you've ever landed on any major airport, it has likely affected you :) That one had a different OS, different requirements and was not something I wrote as a spare-time project, but the overall idea is the same.
